### PR TITLE
[BIT-114] Add Admin Dashboard & its functionality

### PR DESCRIPTION
**Pull request by julix14**
Add Admin Dashboard with userAdministration and Email Administration

### CODE REVIEW

**Comment by Chrissydrx** [comment]
Please add:
- [x] Error message or any response, if the Admin enters invalid credentials
- [x] Remove any console.log
- [x] Check the Code checker
- [x] Changing user data just crashes
- [x] Admin can not change the user professional field decision
- [x] Email Sending: Confirmation is in a different style than every other popup
- [x] The "Zurück zum Dashboard" Button is missing on the "Nutzerverwaltung" page is missing
- [x] Is it possible to have for the Admin Section a different header and nav bar?

**Review by Chrissydrx — DISMISSED** [review]
See other comment

**Comment by julix14** [comment]
> See other comment

Why approve then?

**Comment by Chrissydrx** [comment]
> > See other comment
> 
> Why approve then?

Miss click :(

**Comment by julix14** [comment]
Sollte jetzt alles können, nur das mit den default values in das edit form ist nicht möglich. IDK why

**Review by Chrissydrx — APPROVED** [review]
Looks good

**Pull request merged**
